import "server-only";
import type { AppRole } from "@/lib/auth";

/**
 * Registry of tables exposed through the generic REST layer
 * (`/api/erp/[resource]`). Anything not listed here is not reachable,
 * and every query is company-scoped by `tenantQuery`.
 */
export interface ResourceDef {
  table: string;
  /** Fields matched by the `?q=` search parameter. */
  search: string[];
  /** Relations expanded on list endpoints. */
  expand?: Record<string, unknown>;
  /** Relations expanded on the detail endpoint (defaults to `expand`). */
  expandOne?: Record<string, unknown>;
  /** Default sort. */
  sort?: Record<string, "asc" | "desc">;
  /** Fields accepted from the client on create/update. */
  writable: string[];
  /** Minimum role required to write. Reads require any authenticated tenant user. */
  writeRole?: AppRole;
  /** Fields coerced to numbers before writing. */
  numeric?: string[];
  /** Fields coerced to ISO dates before writing. */
  dates?: string[];
}


export const RESOURCES: Record<string, ResourceDef> = {
  branch: {
    table: "branch",
    search: ["name", "code", "city"],
    expand: { manager: true },
    sort: { name: "asc" },
    writable: ["name", "code", "branch_type", "address", "city", "phone", "email", "manager", "parent_branch", "status", "notes"],
    writeRole: "manager",
  },
  partner: {
    table: "partner",
    search: ["name", "commercial_name", "tax_id", "email", "contact_name"],
    expand: { parent_partner: true },
    expandOne: { parent_partner: true, seller: { _limit: 100 }, authorized_products: true },
    sort: { name: "asc" },
    writable: [
      "name", "commercial_name", "partner_type", "tax_id", "contact_name", "email", "phone", "whatsapp",
      "address", "city", "country", "credit_limit", "credit_days", "currency", "default_commission_pct",
      "logo_url", "status", "contract_from", "contract_to", "commercial_terms", "notes", "parent_partner",
    ],
    numeric: ["credit_limit", "credit_days", "default_commission_pct"],
    dates: ["contract_from", "contract_to"],
    writeRole: "manager",
  },
  seller: {
    table: "seller",
    search: ["first_name", "last_name", "code", "email", "phone"],
    expand: { partner: true, branch: true, supervisor: true },
    expandOne: { partner: true, branch: true, supervisor: true, user: true, authorized_products: true },
    sort: { first_name: "asc" },
    writable: [
      "user", "partner", "branch", "code", "first_name", "last_name", "email", "phone", "whatsapp",
      "seller_role", "commission_pct", "monthly_goal", "max_discount_pct", "currency", "photo_url",
      "hire_date", "status", "notes", "supervisor",
    ],
    numeric: ["commission_pct", "monthly_goal", "max_discount_pct"],
    dates: ["hire_date"],
    writeRole: "manager",
  },
  zone: {
    table: "zone",
    search: ["name"],
    sort: { name: "asc" },
    writable: ["name", "description", "color", "status", "zone_type", "max_capacity",
      "current_occupancy", "requires_wristband"],
    numeric: ["max_capacity", "current_occupancy"],
    writeRole: "manager",
  },
  hotel: {
    table: "hotel",
    search: ["name", "address", "pickup_point"],
    expand: { zone: true },
    sort: { name: "asc" },
    writable: ["zone", "name", "address", "phone", "category", "pickup_point", "latitude", "longitude", "pickup_offset_min", "status", "notes"],
    numeric: ["latitude", "longitude", "pickup_offset_min"],
    writeRole: "operations",
  },
  product_category: {
    table: "product_category",
    search: ["name"],
    sort: { sort_order: "asc" },
    writable: ["name", "description", "color", "icon", "sort_order", "status"],
    numeric: ["sort_order"],
    writeRole: "manager",
  },
  cancellation_policy: {
    table: "cancellation_policy",
    search: ["name"],
    sort: { name: "asc" },
    writable: ["name", "description", "tiers", "no_show_refund_pct", "status"],
    numeric: ["no_show_refund_pct"],
    writeRole: "manager",
  },
  product: {
    table: "product",
    search: ["name", "code", "location"],
    expand: { category: true, product_modality: { _limit: 30 } },
    expandOne: {
      category: true, cancellation_policy: true,
      product_modality: { _limit: 50, _sort: { sort_order: "asc" } },
      product_cost: { _limit: 50, supplier: true },
      price_rule: { _limit: 50, partner: true, modality: true },
      departure: { _limit: 30, _sort: { departure_at: "asc" } },
    },
    sort: { sort_order: "asc" },
    writable: [
      "category", "cancellation_policy", "name", "code", "product_type", "short_description", "description",
      "cover_image_url", "video_url", "location", "meeting_point", "duration_hours", "languages",
      "min_age", "default_capacity", "restrictions", "recommendations", "inclusions", "exclusions",
      "terms", "instructions", "base_price", "base_cost", "currency", "featured", "sort_order", "status",
    ],
    numeric: ["duration_hours", "min_age", "default_capacity", "base_price", "base_cost", "sort_order"],
    writeRole: "manager",
  },
  product_modality: {
    table: "product_modality",
    search: ["name", "code"],
    expand: { product: true },
    sort: { sort_order: "asc" },
    writable: ["product", "name", "code", "modality_type", "price", "cost", "currency", "min_pax", "max_pax", "age_from", "age_to", "capacity_weight", "sort_order", "status"],
    numeric: ["price", "cost", "min_pax", "max_pax", "age_from", "age_to", "capacity_weight", "sort_order"],
    writeRole: "manager",
  },
  price_rule: {
    table: "price_rule",
    search: ["name"],
    expand: { product: true, modality: true, partner: true, seller: true },
    sort: { priority: "asc" },
    writable: ["product", "modality", "partner", "seller", "name", "price_type", "channel", "amount", "currency", "season_from", "season_to", "weekdays", "time_from", "time_to", "min_qty", "max_qty", "priority", "status"],
    numeric: ["amount", "min_qty", "max_qty", "priority"],
    dates: ["season_from", "season_to"],
    writeRole: "manager",
  },
  departure: {
    table: "departure",
    search: ["meeting_point"],
    expand: { product: true, branch: true },
    expandOne: {
      product: true, branch: true,
      booking: { _limit: 300, customer: true, pickup_hotel: true },
      departure_resource: { _limit: 50, vehicle: true, staff: true },
      pickup_route: { _limit: 50, vehicle: true, driver: true, guide: true, zone: true },
    },
    sort: { departure_at: "asc" },
    writable: ["product", "branch", "departure_at", "departure_time", "capacity", "cutoff_hours", "status", "meeting_point", "notes"],
    numeric: ["capacity", "cutoff_hours"],
    dates: ["departure_at"],
    writeRole: "operations",
  },
  customer: {
    table: "customer",
    search: ["first_name", "last_name", "email", "phone", "document_id"],
    expand: { hotel: true, assigned_seller: true },
    expandOne: {
      hotel: true, assigned_seller: true,
      booking: { _limit: 50, _sort: { createdAt: "desc" }, product: true, departure: true },
      order: { _limit: 50, _sort: { createdAt: "desc" } },
      lead: { _limit: 20, _sort: { createdAt: "desc" } },
    },
    sort: { createdAt: "desc" },
    writable: [
      "hotel", "assigned_seller", "first_name", "last_name", "email", "phone", "whatsapp", "nationality",
      "language", "country", "room", "address", "document_id", "birth_date", "tags", "source",
      "status", "preferences", "notes",
    ],
    dates: ["birth_date"],
    writeRole: "seller",
  },
  lead: {
    table: "lead",
    search: ["name", "email", "phone"],
    expand: { customer: true, seller: true, product: true },
    expandOne: { customer: true, seller: true, product: true, partner: true, crm_activity: { _limit: 100, _sort: { createdAt: "desc" }, user: true } },
    sort: { createdAt: "desc" },
    writable: ["customer", "seller", "product", "partner", "name", "email", "phone", "whatsapp", "source", "status", "estimated_value", "currency", "pax", "travel_date", "next_action_at", "lost_reason", "notes"],
    numeric: ["estimated_value", "pax"],
    dates: ["travel_date", "next_action_at"],
    writeRole: "seller",
  },
  crm_activity: {
    table: "crm_activity",
    search: ["subject"],
    expand: { lead: true, customer: true, user: true },
    sort: { createdAt: "desc" },
    writable: ["lead", "customer", "user", "activity_type", "subject", "notes", "due_at", "done_at", "status"],
    dates: ["due_at", "done_at"],
    writeRole: "seller",
  },
  promotion: {
    table: "promotion",
    search: ["name", "code"],
    expand: { products: true },
    sort: { createdAt: "desc" },
    writable: ["name", "code", "discount_type", "value", "valid_from", "valid_to", "max_uses", "used_count", "min_amount", "channels", "status", "description"],
    numeric: ["value", "max_uses", "used_count", "min_amount"],
    dates: ["valid_from", "valid_to"],
    writeRole: "manager",
  },
  order: {
    table: "order",
    search: ["order_number"],
    expand: { customer: true, seller: true, partner: true, branch: true },
    expandOne: {
      customer: true, seller: true, partner: true, branch: true, created_by: true, promotion: true,
      booking: { _limit: 100, product: true, departure: true, modality: true, pickup_hotel: true },
      payment: { _limit: 100, _sort: { createdAt: "desc" }, user: true },
    },
    sort: { createdAt: "desc" },
    writable: ["status", "notes", "channel", "seller", "partner", "branch", "promotion"],
    writeRole: "seller",
  },
  booking: {
    table: "booking",
    search: ["booking_number", "voucher_code", "room_number"],
    expand: { customer: true, product: true, departure: true, seller: true, partner: true, modality: true },
    expandOne: {
      customer: true, product: true, departure: true, seller: true, partner: true, branch: true,
      modality: true, pickup_hotel: true, order: true, created_by: true, checked_in_by: true,
      participant: { _limit: 100 },
      voucher: { _limit: 10 },
      commission: { _limit: 20, seller: true, partner: true },
      payment: { _limit: 50, _sort: { createdAt: "desc" } },
      pickup: { _limit: 10, hotel: true, route: true },
    },
    sort: { createdAt: "desc" },
    writable: ["status", "notes", "internal_notes", "pickup_hotel", "pickup_time", "pickup_location", "room_number", "checkin_status"],
    writeRole: "seller",
  },
  participant: {
    table: "participant",
    search: ["full_name", "document_id"],
    expand: { booking: true },
    sort: { createdAt: "asc" },
    writable: ["booking", "full_name", "age", "category", "document_id", "nationality", "checkin_status", "special_requirements", "notes"],
    numeric: ["age"],
    writeRole: "seller",
  },
  voucher: {
    table: "voucher",
    search: ["code"],
    expand: { booking: { customer: true, product: true, departure: true } },
    sort: { createdAt: "desc" },
    writable: ["status", "notes", "expires_at"],
    dates: ["expires_at"],
    writeRole: "operations",
  },
  commission_rule: {
    table: "commission_rule",
    search: ["name"],
    expand: { product: true, category: true, partner: true, seller: true },
    sort: { priority: "asc" },
    writable: ["name", "priority", "beneficiary_type", "calc_type", "value", "tiers", "product", "category", "partner", "seller", "channel", "season_from", "season_to", "min_sales", "max_sales", "currency", "status", "description"],
    numeric: ["priority", "value", "min_sales", "max_sales"],
    dates: ["season_from", "season_to"],
    writeRole: "admin",
  },
  commission: {
    table: "commission",
    search: ["beneficiary_name"],
    expand: { booking: { product: true }, seller: true, partner: true, rule: true },
    sort: { createdAt: "desc" },
    writable: ["status", "notes"],
    writeRole: "manager",
  },
  settlement: {
    table: "settlement",
    search: ["code"],
    expand: { partner: true, seller: true },
    expandOne: { partner: true, seller: true, approved_by: true, payable: { _limit: 50 } },
    sort: { createdAt: "desc" },
    writable: ["status", "notes", "paid_total", "pending_total"],
    numeric: ["paid_total", "pending_total"],
    writeRole: "manager",
  },
  cash_register: {
    table: "cash_register",
    search: ["name", "code", "terminal"],
    expand: { branch: true },
    sort: { name: "asc" },
    writable: ["branch", "name", "code", "terminal", "currency", "status"],
    writeRole: "manager",
  },
  cash_session: {
    table: "cash_session",
    search: ["code"],
    expand: { cash_register: true, branch: true, user: true },
    expandOne: { cash_register: true, branch: true, user: true, cash_movement: { _limit: 300, _sort: { createdAt: "desc" } } },
    sort: { createdAt: "desc" },
    writable: ["notes"],
    writeRole: "cashier",
  },
  payment: {
    table: "payment",
    search: ["reference"],
    expand: { order: true, booking: true, customer: true, partner: true, user: true },
    sort: { createdAt: "desc" },
    writable: ["status", "notes"],
    writeRole: "cashier",
  },
  receivable: {
    table: "receivable",
    search: ["document_number"],
    expand: { partner: true, customer: true, order: true },
    sort: { due_date: "asc" },
    writable: ["status", "notes", "due_date", "paid_amount", "balance", "aging_bucket"],
    numeric: ["paid_amount", "balance"],
    dates: ["due_date"],
    writeRole: "manager",
  },
  supplier: {
    table: "supplier",
    search: ["name", "tax_id", "contact_name", "email"],
    sort: { name: "asc" },
    writable: ["name", "supplier_type", "tax_id", "contact_name", "email", "phone", "address", "currency", "payment_terms_days", "status", "notes"],
    numeric: ["payment_terms_days"],
    writeRole: "manager",
  },
  payable: {
    table: "payable",
    search: ["concept", "reference"],
    expand: { supplier: true, partner: true, seller: true, settlement: true },
    sort: { due_date: "asc" },
    writable: ["supplier", "partner", "seller", "settlement", "concept", "category", "amount", "paid_amount", "balance", "currency", "issue_date", "due_date", "status", "reference", "notes"],
    numeric: ["amount", "paid_amount", "balance"],
    dates: ["issue_date", "due_date"],
    writeRole: "manager",
  },
  expense_category: {
    table: "expense_category",
    search: ["name"],
    sort: { name: "asc" },
    writable: ["name", "description", "color", "status"],
    writeRole: "manager",
  },
  expense: {
    table: "expense",
    search: ["concept"],
    expand: { category: true, branch: true, supplier: true, user: true },
    sort: { expense_date: "desc" },
    writable: ["category", "branch", "supplier", "cash_session", "concept", "amount", "currency", "exchange_rate", "expense_date", "payment_method", "status", "notes"],
    numeric: ["amount", "exchange_rate"],
    dates: ["expense_date"],
    writeRole: "cashier",
  },
  currency_rate: {
    table: "currency_rate",
    search: ["source"],
    sort: { rate_date: "desc" },
    writable: ["currency_from", "currency_to", "rate", "rate_date", "source"],
    numeric: ["rate"],
    dates: ["rate_date"],
    writeRole: "manager",
  },
  staff: {
    table: "staff",
    search: ["full_name", "phone", "email", "document_id"],
    expand: { supplier: true },
    sort: { full_name: "asc" },
    writable: ["supplier", "user", "full_name", "staff_type", "languages", "phone", "email", "document_id", "photo_url", "daily_rate", "currency", "hire_date", "license_expiry", "status", "notes"],
    numeric: ["daily_rate"],
    dates: ["hire_date", "license_expiry"],
    writeRole: "operations",
  },
  vehicle: {
    table: "vehicle",
    search: ["name", "plate"],
    expand: { supplier: true, driver: true },
    sort: { name: "asc" },
    writable: ["supplier", "driver", "name", "plate", "vehicle_type", "capacity", "photo_url", "insurance_expiry", "inspection_expiry", "status", "notes"],
    numeric: ["capacity"],
    dates: ["insurance_expiry", "inspection_expiry"],
    writeRole: "operations",
  },
  product_cost: {
    table: "product_cost",
    search: ["concept"],
    expand: { product: true, supplier: true },
    sort: { createdAt: "desc" },
    writable: ["product", "supplier", "concept", "cost_type", "amount", "currency", "status", "notes"],
    numeric: ["amount"],
    writeRole: "manager",
  },
  pickup_route: {
    table: "pickup_route",
    search: ["name"],
    expand: { departure: { product: true }, zone: true, vehicle: true, driver: true, guide: true },
    expandOne: { departure: { product: true }, zone: true, vehicle: true, driver: true, guide: true, pickup: { _limit: 200, hotel: true, booking: { customer: true } } },
    sort: { start_time: "asc" },
    writable: ["departure", "zone", "vehicle", "driver", "guide", "name", "start_time", "pax_total", "stops_count", "status", "notes"],
    numeric: ["pax_total", "stops_count"],
    writeRole: "operations",
  },
  pickup: {
    table: "pickup",
    search: ["location", "room"],
    expand: { booking: { customer: true, product: true }, hotel: true, route: true },
    sort: { pickup_time: "asc" },
    writable: ["booking", "hotel", "route", "pickup_time", "location", "room", "pax", "status", "notes"],
    numeric: ["pax"],
    writeRole: "operations",
  },
  departure_resource: {
    table: "departure_resource",
    search: ["notes"],
    expand: { departure: { product: true }, vehicle: true, staff: true },
    sort: { createdAt: "desc" },
    writable: ["departure", "vehicle", "staff", "resource_role", "pax_assigned", "start_time", "end_time", "cost", "currency", "status", "notes"],
    numeric: ["pax_assigned", "cost"],
    writeRole: "operations",
  },
  audit_log: {
    table: "audit_log",
    search: ["action", "description", "entity_type"],
    expand: { user: true, impersonated_by: true },
    sort: { createdAt: "desc" },
    writable: [],
    writeRole: "admin",
  },

  // ==========================================================================
  // Blueprint modules: parque, seguridad, mantenimiento, comercio,
  // experiencia del visitante, distribución, contabilidad, equipo y
  // administración. Cada entrada habilita CRUD multi-tenant completo
  // a través de /api/erp/[resource].
  // ==========================================================================
  attraction: {
    table: "attraction",
    search: ["name", "code", "location"],
    expand: { zone: true },
    sort: { name: "asc" },
    writable: ["name", "code", "attraction_type", "operational_status", "capacity_hour", "capacity_simultaneous", "queue_minutes", "guests_today", "duration_min", "min_height_cm", "max_height_cm", "min_age", "max_weight_kg", "health_restrictions", "requires_waiver", "weather_sensitive", "downtime_minutes_today", "last_status_at", "cover_image_url", "location", "status", "notes", "zone"],
    numeric: ["capacity_hour", "capacity_simultaneous", "queue_minutes", "guests_today", "duration_min", "min_height_cm", "max_height_cm", "min_age", "max_weight_kg", "downtime_minutes_today"],
    dates: ["last_status_at"],
    writeRole: "manager",
  },
  attraction_log: {
    table: "attraction_log",
    search: ["reason", "to_status"],
    expand: { attraction: true, user: true },
    sort: { createdAt: "desc" },
    writable: [],
    numeric: ["duration_min", "guests"],
    dates: ["logged_at"],
    writeRole: "operations",
  },
  access_ticket: {
    table: "access_ticket",
    search: ["code", "holder_name", "wristband_code"],
    expand: { customer: true, product: true, booking: true },
    sort: { createdAt: "desc" },
    writable: ["code", "ticket_type", "status", "valid_from", "valid_to", "entries_allowed", "entries_used", "issued_at", "redeemed_at", "qr_payload", "wristband_code", "holder_name", "price", "currency", "notes", "booking", "participant", "customer", "product", "order", "membership"],
    numeric: ["entries_allowed", "entries_used", "price"],
    dates: ["valid_from", "valid_to", "issued_at", "redeemed_at"],
    writeRole: "cashier",
  },
  waiver_template: {
    table: "waiver_template",
    search: ["name", "version", "jurisdiction"],
    sort: { name: "asc" },
    writable: ["name", "version", "jurisdiction", "language", "body", "requires_guardian", "min_age_self_sign", "valid_from", "valid_to", "status"],
    numeric: ["min_age_self_sign"],
    dates: ["valid_from", "valid_to"],
    writeRole: "admin",
  },
  waiver: {
    table: "waiver",
    search: ["signature_name", "document_id", "guardian_name"],
    expand: { waiver_template: true, participant: true, customer: true },
    sort: { createdAt: "desc" },
    writable: ["signed_at", "signature_name", "signature_data", "document_id", "document_type", "template_version", "body_snapshot", "guardian_name", "guardian_document", "status", "valid_until", "ip_address", "channel", "health_flags", "waiver_template", "participant", "customer", "booking", "product"],
    dates: ["signed_at", "valid_until"],
    writeRole: "cashier",
  },
  incident: {
    table: "incident",
    search: ["code", "title", "description", "location"],
    expand: { attraction: true, asset: true, reported_by: true, assigned_to: true },
    sort: { createdAt: "desc" },
    writable: ["code", "occurred_at", "reported_at", "severity", "incident_type", "status", "title", "description", "location", "immediate_action", "root_cause", "witnesses", "medical_attention", "evacuation", "authority_notified", "insurance_claim", "estimated_cost", "currency", "closed_at", "photos", "attraction", "asset", "zone", "participant", "booking", "customer", "vehicle", "reported_by", "assigned_to", "departure"],
    numeric: ["estimated_cost"],
    dates: ["occurred_at", "reported_at", "closed_at"],
    writeRole: "operations",
  },
  incident_action: {
    table: "incident_action",
    search: ["action", "description"],
    expand: { incident: true, assigned_to: true },
    sort: { createdAt: "desc" },
    writable: ["action", "description", "due_date", "completed_at", "status", "priority", "verification_notes", "incident", "assigned_to", "verified_by"],
    dates: ["due_date", "completed_at"],
    writeRole: "operations",
  },
  inspection_template: {
    table: "inspection_template",
    search: ["name", "code"],
    expand: { asset: true, attraction: true },
    sort: { name: "asc" },
    writable: ["name", "code", "frequency", "category", "checklist", "pass_threshold", "requires_signature", "blocks_operation_on_fail", "estimated_min", "status", "asset", "attraction"],
    numeric: ["pass_threshold", "estimated_min"],
    writeRole: "manager",
  },
  inspection: {
    table: "inspection",
    search: ["findings", "signature_name"],
    expand: { inspection_template: true, asset: true, attraction: true, performed_by: true },
    sort: { createdAt: "desc" },
    writable: ["performed_at", "result", "score", "items_total", "items_failed", "findings", "signature_name", "blocked_operation", "photos", "next_due_at", "inspection_template", "asset", "attraction", "vehicle", "performed_by", "work_order"],
    numeric: ["score", "items_total", "items_failed"],
    dates: ["performed_at", "next_due_at"],
    writeRole: "operations",
  },
  asset: {
    table: "asset",
    search: ["name", "code", "serial_number", "location"],
    expand: { zone: true, attraction: true, supplier: true },
    sort: { name: "asc" },
    writable: ["name", "code", "asset_type", "operational_status", "blocks_capacity", "criticality", "serial_number", "location", "capacity", "purchase_date", "purchase_cost", "currency", "warranty_until", "meter_hours", "meter_km", "next_maintenance_at", "downtime_minutes_month", "status", "notes", "zone", "vehicle", "supplier", "branch", "attraction"],
    numeric: ["capacity", "purchase_cost", "meter_hours", "meter_km", "downtime_minutes_month"],
    dates: ["purchase_date", "warranty_until", "next_maintenance_at"],
    writeRole: "manager",
  },
  work_order: {
    table: "work_order",
    search: ["code", "title", "description"],
    expand: { asset: true, attraction: true, assigned_to: true, supplier: true },
    sort: { createdAt: "desc" },
    writable: ["code", "title", "order_type", "priority", "status", "opened_at", "scheduled_at", "started_at", "finished_at", "description", "work_performed", "downtime_min", "labor_hours", "labor_cost", "parts_cost", "total_cost", "currency", "takes_asset_down", "meter_reading", "asset", "attraction", "vehicle", "assigned_to", "supplier", "incident", "maintenance_plan", "requested_by"],
    numeric: ["downtime_min", "labor_hours", "labor_cost", "parts_cost", "total_cost", "meter_reading"],
    dates: ["opened_at", "scheduled_at", "started_at", "finished_at"],
    writeRole: "operations",
  },
  maintenance_plan: {
    table: "maintenance_plan",
    search: ["name"],
    expand: { asset: true, attraction: true, vehicle: true },
    sort: { next_due_at: "asc" },
    writable: ["name", "trigger_type", "interval_days", "interval_hours", "interval_km", "lead_time_days", "task_list", "estimated_min", "estimated_cost", "last_executed_at", "next_due_at", "takes_asset_down", "status", "asset", "attraction", "vehicle", "inspection_template", "staff"],
    numeric: ["interval_days", "interval_hours", "interval_km", "lead_time_days", "estimated_min", "estimated_cost"],
    dates: ["last_executed_at", "next_due_at"],
    writeRole: "manager",
  },
  warehouse: {
    table: "warehouse",
    search: ["name", "code", "location"],
    expand: { branch: true, zone: true },
    sort: { name: "asc" },
    writable: ["name", "code", "warehouse_type", "location", "allows_negative", "status", "notes", "branch", "zone"],
    writeRole: "manager",
  },
  inventory_item: {
    table: "inventory_item",
    search: ["name", "sku", "barcode"],
    expand: { product_category: true, supplier: true },
    sort: { name: "asc" },
    writable: ["name", "sku", "barcode", "item_type", "unit", "cost", "price", "currency", "tax_rate", "min_stock", "max_stock", "reorder_point", "reorder_qty", "shelf_life_days", "is_sellable", "tracks_lots", "image_url", "status", "product_category", "supplier", "product"],
    numeric: ["cost", "price", "tax_rate", "min_stock", "max_stock", "reorder_point", "reorder_qty", "shelf_life_days"],
    writeRole: "manager",
  },
  stock_level: {
    table: "stock_level",
    search: [],
    expand: { warehouse: true, inventory_item: true },
    sort: { available: "asc" },
    writable: ["quantity", "reserved", "available", "avg_cost", "last_movement_at", "last_counted_at", "warehouse", "inventory_item"],
    numeric: ["quantity", "reserved", "available", "avg_cost"],
    dates: ["last_movement_at", "last_counted_at"],
    writeRole: "manager",
  },
  stock_movement: {
    table: "stock_movement",
    search: ["reference", "reason", "lot_code"],
    expand: { warehouse: true, inventory_item: true, user: true },
    sort: { createdAt: "desc" },
    writable: ["movement_type", "quantity", "unit_cost", "total_cost", "currency", "moved_at", "balance_after", "reason", "reference", "lot_code", "expires_at", "warehouse", "to_warehouse", "inventory_item", "user", "purchase_order", "order", "work_order"],
    numeric: ["quantity", "unit_cost", "total_cost", "balance_after"],
    dates: ["moved_at", "expires_at"],
    writeRole: "operations",
  },
  purchase_order: {
    table: "purchase_order",
    search: ["code", "notes"],
    expand: { supplier: true, warehouse: true, requested_by: true },
    sort: { createdAt: "desc" },
    writable: ["code", "status", "ordered_at", "expected_at", "received_at", "subtotal", "tax", "total", "currency", "exchange_rate", "payment_terms", "notes", "approval_notes", "supplier", "warehouse", "requested_by", "approved_by", "payable"],
    numeric: ["subtotal", "tax", "total", "exchange_rate"],
    dates: ["ordered_at", "expected_at", "received_at"],
    writeRole: "manager",
  },
  purchase_order_line: {
    table: "purchase_order_line",
    search: ["description"],
    expand: { purchase_order: true, inventory_item: true },
    sort: { createdAt: "desc" },
    writable: ["description", "quantity", "quantity_received", "unit_cost", "tax_rate", "line_total", "purchase_order", "inventory_item"],
    numeric: ["quantity", "quantity_received", "unit_cost", "tax_rate", "line_total"],
    writeRole: "manager",
  },
  membership_plan: {
    table: "membership_plan",
    search: ["name", "code"],
    sort: { price: "asc" },
    writable: ["name", "code", "plan_type", "price", "currency", "duration_days", "visits_included", "guest_passes", "discount_percent", "benefits", "blackout_dates", "auto_renew", "image_url", "status"],
    numeric: ["price", "duration_days", "visits_included", "guest_passes", "discount_percent"],
    writeRole: "manager",
  },
  membership: {
    table: "membership",
    search: ["code"],
    expand: { membership_plan: true, customer: true },
    sort: { createdAt: "desc" },
    writable: ["code", "status", "starts_at", "ends_at", "visits_used", "guest_passes_used", "amount_paid", "currency", "auto_renew", "photo", "last_visit_at", "cancelled_at", "cancel_reason", "membership_plan", "customer", "order"],
    numeric: ["visits_used", "guest_passes_used", "amount_paid"],
    dates: ["starts_at", "ends_at", "last_visit_at", "cancelled_at"],
    writeRole: "cashier",
  },
  gift_card: {
    table: "gift_card",
    search: ["code", "recipient_name", "recipient_email"],
    expand: { customer: true },
    sort: { createdAt: "desc" },
    writable: ["code", "status", "initial_amount", "balance", "currency", "issued_at", "expires_at", "recipient_name", "recipient_email", "message", "delivery_channel", "customer", "order", "product"],
    numeric: ["initial_amount", "balance"],
    dates: ["issued_at", "expires_at"],
    writeRole: "cashier",
  },
  gift_card_movement: {
    table: "gift_card_movement",
    search: ["notes"],
    expand: { gift_card: true, user: true },
    sort: { createdAt: "desc" },
    writable: ["movement_type", "amount", "balance_after", "moved_at", "notes", "gift_card", "order", "user"],
    numeric: ["amount", "balance_after"],
    dates: ["moved_at"],
    writeRole: "cashier",
  },
  guest_case: {
    table: "guest_case",
    search: ["code", "subject", "description"],
    expand: { customer: true, booking: true, assigned_to: true },
    sort: { createdAt: "desc" },
    writable: ["code", "case_type", "status", "priority", "channel", "opened_at", "subject", "description", "resolution", "resolved_at", "satisfaction_score", "compensation_amount", "currency", "compensation_type", "customer", "booking", "participant", "assigned_to", "order", "incident"],
    numeric: ["satisfaction_score", "compensation_amount"],
    dates: ["opened_at", "resolved_at"],
    writeRole: "operations",
  },
  quote: {
    table: "quote",
    search: ["code", "notes"],
    expand: { customer: true, partner: true, seller: true },
    sort: { createdAt: "desc" },
    writable: ["code", "status", "quote_type", "issued_at", "valid_until", "event_date", "pax", "subtotal", "discount", "tax", "total", "currency", "margin_percent", "terms", "notes", "rejection_reason", "sent_at", "decided_at", "customer", "partner", "seller", "lead", "order", "user"],
    numeric: ["pax", "subtotal", "discount", "tax", "total", "margin_percent"],
    dates: ["issued_at", "valid_until", "event_date", "sent_at", "decided_at"],
    writeRole: "seller",
  },
  quote_line: {
    table: "quote_line",
    search: ["description"],
    expand: { quote: true, product: true },
    sort: { createdAt: "desc" },
    writable: ["description", "quantity", "unit_price", "unit_cost", "discount_percent", "line_total", "service_date", "quote", "product", "product_modality", "departure"],
    numeric: ["quantity", "unit_price", "unit_cost", "discount_percent", "line_total"],
    dates: ["service_date"],
    writeRole: "seller",
  },
  allotment: {
    table: "allotment",
    search: ["notes"],
    expand: { partner: true, product: true, departure: true },
    sort: { valid_from: "asc" },
    writable: ["allotment_type", "seats", "seats_used", "seats_released", "release_days", "valid_from", "valid_to", "weekdays", "status", "notes", "partner", "product", "departure", "product_modality"],
    numeric: ["seats", "seats_used", "seats_released", "release_days"],
    dates: ["valid_from", "valid_to"],
    writeRole: "manager",
  },
  ledger_account: {
    table: "ledger_account",
    search: ["code", "name"],
    expand: { parent: true },
    sort: { code: "asc" },
    writable: ["code", "name", "account_type", "subledger", "normal_side", "is_postable", "currency", "balance", "status", "parent"],
    numeric: ["balance"],
    writeRole: "admin",
  },
  ledger_entry: {
    table: "ledger_entry",
    search: ["entry_code", "memo", "period"],
    expand: { ledger_account: true, order: true, payment: true },
    sort: { createdAt: "desc" },
    writable: [],
    numeric: ["line_no", "debit", "credit", "exchange_rate", "amount_base"],
    dates: ["posted_at"],
    writeRole: "admin",
  },
  invoice: {
    table: "invoice",
    search: ["number", "ncf", "customer_name", "customer_tax_id"],
    expand: { customer: true, order: true, partner: true },
    sort: { createdAt: "desc" },
    writable: ["number", "series", "ncf", "ncf_type", "invoice_type", "status", "issued_at", "due_date", "subtotal", "tax", "tax_rate", "discount", "total", "paid_amount", "currency", "exchange_rate", "customer_name", "customer_tax_id", "customer_address", "notes", "pdf_url", "efac_status", "efac_track_id", "voided_at", "void_reason", "customer", "order", "partner", "settlement", "tax_profile", "user"],
    numeric: ["subtotal", "tax", "tax_rate", "discount", "total", "paid_amount", "exchange_rate"],
    dates: ["issued_at", "due_date", "voided_at"],
    writeRole: "manager",
  },
  tax_profile: {
    table: "tax_profile",
    search: ["name", "tax_name", "ncf_series"],
    sort: { name: "asc" },
    writable: ["name", "country", "tax_name", "tax_rate", "included_in_price", "tourism_tax_rate", "service_charge_rate", "tax_id_label", "ncf_series", "ncf_next", "ncf_expires", "efac_enabled", "rounding", "status"],
    numeric: ["tax_rate", "tourism_tax_rate", "service_charge_rate", "ncf_next"],
    dates: ["ncf_expires"],
    writeRole: "admin",
  },
  shift: {
    table: "shift",
    search: ["role_label", "notes"],
    expand: { staff: true, zone: true, attraction: true },
    sort: { starts_at: "asc" },
    writable: ["shift_date", "starts_at", "ends_at", "role_label", "status", "break_min", "hours_planned", "hourly_rate", "currency", "notes", "staff", "zone", "attraction", "branch", "departure", "user"],
    numeric: ["break_min", "hours_planned", "hourly_rate"],
    dates: ["shift_date", "starts_at", "ends_at"],
    writeRole: "manager",
  },
  attendance: {
    table: "attendance",
    search: ["notes"],
    expand: { staff: true, shift: true },
    sort: { createdAt: "desc" },
    writable: ["attendance_date", "clock_in", "clock_out", "hours_worked", "overtime_hours", "status", "method", "notes", "staff", "shift", "approved_by"],
    numeric: ["hours_worked", "overtime_hours"],
    dates: ["attendance_date", "clock_in", "clock_out"],
    writeRole: "operations",
  },
  certification: {
    table: "certification",
    search: ["name", "number", "issuer"],
    expand: { staff: true },
    sort: { expires_at: "asc" },
    writable: ["name", "cert_type", "issuer", "number", "issued_at", "expires_at", "status", "blocks_assignment", "document", "notes", "staff"],
    dates: ["issued_at", "expires_at"],
    writeRole: "manager",
  },
  task: {
    table: "task",
    search: ["title", "description"],
    expand: { assigned_to: true, created_by: true },
    sort: { due_at: "asc" },
    writable: ["title", "description", "status", "priority", "due_at", "completed_at", "task_type", "source", "checklist", "assigned_to", "created_by", "booking", "order", "incident", "work_order", "guest_case", "customer", "lead"],
    dates: ["due_at", "completed_at"],
    writeRole: "seller",
  },
  document: {
    table: "document",
    search: ["title", "version"],
    expand: { owner: true },
    sort: { title: "asc" },
    writable: ["title", "doc_type", "version", "body", "file", "url", "effective_from", "expires_at", "requires_ack", "audience", "status", "owner"],
    dates: ["effective_from", "expires_at"],
    writeRole: "manager",
  },
  document_ack: {
    table: "document_ack",
    search: ["version_acked"],
    expand: { document: true, user: true },
    sort: { createdAt: "desc" },
    writable: [],
    numeric: ["quiz_score"],
    dates: ["acknowledged_at"],
    writeRole: "seller",
  },
  approval_request: {
    table: "approval_request",
    search: ["code", "reason", "target_id"],
    expand: { requested_by: true, approved_by: true },
    sort: { createdAt: "desc" },
    writable: ["code", "action_type", "status", "requested_at", "decided_at", "amount", "currency", "reason", "decision_notes", "payload", "target_table", "target_id", "requires_two", "expires_at", "requested_by", "approved_by", "second_approver", "order", "booking", "payment", "purchase_order"],
    numeric: ["amount"],
    dates: ["requested_at", "decided_at", "expires_at"],
    writeRole: "manager",
  },
  integration: {
    table: "integration",
    search: ["name", "external_id"],
    expand: { partner: true },
    sort: { name: "asc" },
    writable: ["name", "provider", "category", "status", "direction", "endpoint_url", "external_id", "last_sync_at", "last_error", "sync_frequency", "records_synced", "config", "webhook_secret_set", "partner", "user"],
    numeric: ["records_synced"],
    dates: ["last_sync_at"],
    writeRole: "admin",
  },
  notification: {
    table: "notification",
    search: ["title"],
    expand: { user: true, partner: true },
    sort: { createdAt: "desc" },
    writable: ["read_status", "read_at"],
    writeRole: "seller",
  },
};

export function getResource(name: string): ResourceDef | null {
  return RESOURCES[name] ?? null;
}

/** Filters and coerces an incoming payload down to the resource's writable fields. */
export function sanitizePayload(def: ResourceDef, body: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const key of def.writable) {
    if (!(key in body)) continue;
    let value = body[key];
    if (value === "" || value === undefined) value = null;
    if (value !== null && def.numeric?.includes(key)) {
      const n = Number(value);
      value = Number.isFinite(n) ? n : null;
    }
    if (value !== null && def.dates?.includes(key)) {
      const d = new Date(value as string);
      value = Number.isNaN(d.getTime()) ? null : d.toISOString();
    }
    if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      value = JSON.stringify(value);
    }
    out[key] = value ?? undefined;
  }
  return out;
}
